query getAllForms {
  species: pokemon_v2_pokemonspecies {
    name
    pokemon: pokemon_v2_pokemons(where: {name: {_nregex: "-(mega|gmax|busted|totem|original|eternal|phony|gulping|gorging|sunshine|antique|hangry|dada|zen|fancy|poke-ball|shock|chill|douse|burn)"}}) {
      id
      name
      default: is_default
      forms: pokemon_v2_pokemonforms(where: {name: {_nregex: "-(mega|gmax|busted|totem|original|eternal|phony|gulping|gorging|sunshine|antique|hangry|dada|zen|fancy|poke-ball|shock|chill|douse|burn)"}}) {
        name
        formName: form_name
        default: is_default
      }
      moves: pokemon_v2_pokemonmoves(distinct_on: [move_id]) {
        move: pokemon_v2_move {
          name
        }
      }
    }
  }
}
